### PR TITLE
Support Basic responsive design (for real)

### PR DESCRIPTION
**Pull request by ethanresnick**

### CODE REVIEW

**Comment by ethanresnick** [comment]
Hey, I didn't realize that this PR would bring along commits I made after first opening the PR. If you just want to merge in the responsive design stuff, without bower/amd/etc, go back to [b41266e](https://github.com/ethanresnick/skrollr-stylesheets/commit/b41266ecd79f033531188aacfcaa67d429bc5c14), the diff of which is very easy to follow. (You'll also need to grab the bugfix from [this commit](https://github.com/ethanresnick/skrollr-stylesheets/commit/ec303ff549c70649122a3f122dd36f0b51bc1383)). Sorry for the confusion; I'm still learning my way around git.

Note also that, these changes are breaking: on resize, when I wipe out all the old attributes (as they may not apply at the new screen size), I don't preserve the original inline attributes, for simplicity's sake. I figure most people will either be using a stylesheet to configure skrollr, or the inline attributes, but not both.

**Comment by Prinzhorn** [comment]
Thanks for this PR. I'm sorry, but I don't have the time to do this manually.

Some tips for next time:
- Never use the `master` branch for pull request. Create a `responsive_support` branch or similar and never touch it again (delete it after it has been merged).
- Read about `git rebase` to make pull requests cleaner by squashing multiple commits into one.

> Note also that, these changes are breaking: on resize, when I wipe out all the old attributes (as they may not apply at the new screen size), I don't preserve the original inline attributes, for simplicity's sake.

We can talk about this again if you create a new PR. skrollr itself does preserve them.

**Comment by dahannes** [comment]
@ethanresnick 

I cannot get your PR to work correctly. Is this actually supposed to work on HTML-content that is added dynamically via ajax? And can it be done without using AMD / Bower? 
Could you please provide some more information on how to set this up correctly?

(What I am trying to do: empty #skrollr-body, append new content to it, rerun / apply skrollr-stylesheets on new content)

**Comment by ethanresnick** [comment]
@dahannes 

The short answer is no, it's not meant to work for Ajax-added content. It still follows the original plugin's model of finding the elements that match each CSS selector (at the time the CSS is parsed) and applying the relevant skrollr instructions to the DOM of each element. But you could get it to work with some relatively-simple modifications (namely, exposing `saveKeyframesToDOM` and calling that when your new elements are loaded). It's the same story for AMD/Bower: it doesn't work without those yet, but making it do so would be a relatively easy change. I can't get to making any of those changes (or offering better docs) for a couple weeks, but then I will try to do so. If you have any other issues, open a thread on my fork so we don't pollute this one.

Thanks.

**Comment by dahannes** [comment]
Thanks! I was actually looking the wrong way. After I updated some other variables I could reload the stylesheets function and refresh skrollr.

**Pull request closed without merging**
